services:
  - type: web
    name: bg-text-corrector
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: GROQ_API_KEY
        sync: false
